[[project]]
name = "bookstore"
desc = "Create a modern web app with clean architecture using NestJS + MongoDB & ViteJS + React"
tags = ["nestjs", "mongodb", "vitejs", "react"]
img = "/img/bookstore.webp"
links = [
  { name = "github", url = "https://github.com/tduyng/bookstore" },
  { name = "demo", url = "https://bookzeta.netlify.app" },
]

[[project]]
name = "ecommerce-graphql"
desc = "Ecommerce project using GraphQL with stack: NestJS - ReactJS(NextJS) - MongoDB"
tags = ["nestjs", "nextjs", "mongodb"]
img = "/img/ecommerce.webp"
links = [
  { name = "github", url = "https://github.com/tduyng/ecommerce" },
]


[[project]]
name = "nestjs-flow"
desc = "End to end build a project with NestJS. This series demo is just for learning or practicing purpose on NestJS"
tags = ["nestjs", "auth", "postgresql","aws","elastic"]
links = [
  { name = "github", url = "https://github.com/tduyng/nestjs-flow" },
]

[[project]]
name = "nestjs-graphql"
desc = "Explore the integration of NestJS, GraphQL, and Prisma. The project aims to demonstrate how to develop a clean, scalable, and testable architecture."
tags = ["nestjs", "postgresql","prisma","graphql"]
links = [
  { name = "github", url = "https://github.com/tduyng/nestjs-graphql-prisma" },
]

[[project]]
name = "react-ant-demo"
desc = "Demo using React, TypeScript, Ant Design"
tags = ["react", "typescript","antd"]
img = "/img/react_antd.webp"
links = [
  { name = "github", url = "https://github.com/tduyng/react-antd-demo" },
  { name = "demo", url = "https://react-ant-demo.netlify.app" },
]

[[project]]
name = "rdis"
desc = "Build your own Redis in Rust"
tags = ["rust", "redis"]
links = [
  { name = "github", url = "https://github.com/tduyng/rdis" }
]

[[project]]
name = "revit-api"
desc = "Revit-WPF template 2018-2020+ for Revit API (C#)"
tags = ["revit-api", "c#", "wpf"]
links = [
  { name = "github", url = "https://github.com/tduyng/rdis" }
]